steps:
    # Install webapp
    - name: 'gcr.io/cloud-builders/npm:node-10.15.1'
      id: 'webapp install'
      args: ['install']
      dir: 'webapp'
      waitFor: ['-']
  
    # Lint webapp
    - name: 'gcr.io/cloud-builders/npm:node-10.15.1'
      id: 'webapp lint'
      args: ['run', 'lint']
      dir: 'webapp'
      waitFor: ['webapp install']
  
    # Generate static data
    - name: 'gcr.io/cloud-builders/npm:node-10.15.1'
      id: 'webapp generate:data'
      args: ['run', 'generate:data']
      dir: 'webapp'
      waitFor: ['webapp install']

    # Generate static webapp
    - name: 'gcr.io/cloud-builders/npm:node-10.15.1'
      id: 'webapp generate'
      args: ['run', 'generate']
      dir: 'webapp'
      waitFor: ['webapp generate:data']
  
    # Deploy static webapp
    - name: "gcr.io/$PROJECT_ID/firebase"
      args: ["deploy", "--only", "hosting", "--force", "--project=$PROJECT_ID", "--token", "$_FIREBASE_TOKEN"]
      dir: 'src/services/admin'
      id: "firebase deploy"
